<script lang="ts">
  import { onMount } from 'svelte';
  import { goto } from '$app/navigation';
  import { uiStore } from '$lib/stores/ui.svelte';
  import { supabase } from '$lib/supabaseClient';
  import { formatCurrency, getImageKitUrl } from '$lib/types/product';
  import type { CompleteProduct, DBProduct, DBProductVariant, DBProductImage } from '$lib/types/product';
  import { STANDARD_SIZE_MAP, formatSizeDisplay, findSizeOption } from '$lib/sizes';

  interface Props {
    productId?: string | null;
    initialData?: CompleteProduct | null;
  }

  let { productId = null, initialData = null }: Props = $props();

  // Wizard Step (1: Info, 2: Variants, 3: Images, 4: Review & Publish)
  let currentStep = $state<1 | 2 | 3 | 4>(1);

  // Loading / Saving states
  let isSaving = $state(false);
  let isUploading = $state(false);
  let uploadProgress = $state<string | null>(null);
  let uploadError = $state<string | null>(null);

  // Helper: Slugify
  function slugify(text: string): string {
    return text
      .toString()
      .toLowerCase()
      .trim()
      .replace(/[\s_]+/g, '-')
      .replace(/[^\w-]+/g, '')
      .replace(/--+/g, '-');
  }

  // Predefined quick palette
  const QUICK_PALETTE = [
    { name: 'Blush Pink', hex: '#f4a7c3' },
    { name: 'Peach', hex: '#ffb347' },
    { name: 'Lavender', hex: '#c9a0dc' },
    { name: 'Mint Green', hex: '#7ecba1' },
    { name: 'Coral', hex: '#ff7f6e' },
    { name: 'Classic Black', hex: '#1a1a1a' },
    { name: 'Off White', hex: '#f5f0eb' },
    { name: 'Nude Tan', hex: '#d4a574' },
    { name: 'Champagne Gold', hex: '#d4a853' },
    { name: 'Navy Blue', hex: '#24334a' },
    { name: 'Burgundy', hex: '#631d2f' },
    { name: 'Sage Green', hex: '#879f84' }
  ];

  const PRESET_CATEGORIES = [
    'Slippers',
    'Flats',
    'Heels',
    'Sandals',
    'Loafers',
    'Mules',
    'Slides',
    'Accessories'
  ];

  // Form State
  interface LocalVariant {
    id?: string;
    sku: string;
    color_name: string;
    color_slug: string;
    color_hex: string;
    attributes: Record<string, any>;
    size_stock: Record<string, number>;
    price_override: string | number | null;
    compare_at_price: string | number | null;
    stock_quantity: number;
    is_default: boolean;
    position: number;
    images: DBProductImage[];
  }

  let productForm = $state({
    id: productId || '',
    name: '',
    slug: '',
    brand: 'French Toes',
    category: 'Slippers',
    base_price: '1499',
    compare_at_price: '1999',
    sizes: ['36', '37', '38', '39', '40', '41'] as string[],
    description: '',
    status: 'published' as 'draft' | 'published' | 'archived'
  });

  let slugAutoGenerated = $state(true);

  let variants = $state<LocalVariant[]>([
    {
      id: crypto.randomUUID(),
      sku: 'FT-BLUSH',
      color_name: 'Blush Pink',
      color_slug: 'blush-pink',
      color_hex: '#f4a7c3',
      attributes: {},
      size_stock: { '36': 10, '37': 10, '38': 10, '39': 10, '40': 10, '41': 10 },
      price_override: '',
      compare_at_price: '',
      stock_quantity: 60,
      is_default: true,
      position: 0,
      images: []
    }
  ]);

  // Step 3 active variant tab
  let activeVariantTabId = $state<string>('');

  // Step 4 Storefront Preview State
  let previewSelectedVariantIndex = $state(0);
  let previewActiveImageIndex = $state(0);
  let previewSelectedSize = $state<string>('38');

  const previewVariant = $derived(variants[previewSelectedVariantIndex] || variants[0]);
  const previewPriceNumber = $derived(
    previewVariant?.price_override
      ? parseFloat(String(previewVariant.price_override))
      : (parseFloat(productForm.base_price) || 0)
  );
  const previewOriginalPriceNumber = $derived(
    previewVariant?.compare_at_price
      ? parseFloat(String(previewVariant.compare_at_price))
      : (productForm.compare_at_price ? parseFloat(productForm.compare_at_price) : null)
  );
  const previewPrice = $derived(formatCurrency(previewPriceNumber));
  const previewOriginalPrice = $derived(previewOriginalPriceNumber ? formatCurrency(previewOriginalPriceNumber) : null);
  const previewSelectedSizeStock = $derived(
    previewSelectedSize ? getVariantSizeStock(previewVariant, previewSelectedSize) : 0
  );

  // Drag and drop image reordering state
  let draggedImageIndex = $state<number | null>(null);

  // ─── Size Stock Helper Functions ──────────────────────────────────────────
  function getVariantSizeStock(v: LocalVariant, size: string): number {
    if (v.size_stock && v.size_stock[size] !== undefined) {
      return Number(v.size_stock[size]) || 0;
    }
    return 0;
  }

  function updateVariantSizeStock(variantIndex: number, size: string, qtyStr: string) {
    const qty = parseInt(qtyStr, 10);
    const cleanQty = isNaN(qty) ? 0 : Math.max(0, qty);
    const v = variants[variantIndex];
    if (!v.size_stock) v.size_stock = {};
    v.size_stock[size] = cleanQty;

    // Recalculate total stock for this variant
    const total = Object.values(v.size_stock).reduce((acc, n) => acc + (Number(n) || 0), 0);
    v.stock_quantity = total;
  }

  function fillVariantSizesWithQty(variantIndex: number, qty: number) {
    const v = variants[variantIndex];
    if (!v.size_stock) v.size_stock = {};
    for (const sz of productForm.sizes) {
      v.size_stock[sz] = qty;
    }
    v.stock_quantity = qty * productForm.sizes.length;
    uiStore.addToast(`Set all sizes to ${qty} pcs for ${v.color_name}`, 'info');
  }

  function toggleProductSize(size: string) {
    if (productForm.sizes.includes(size)) {
      if (productForm.sizes.length <= 1) {
        uiStore.addToast('At least one size must remain active for the product.', 'error');
        return;
      }
      productForm.sizes = productForm.sizes.filter(s => s !== size);
    } else {
      const allKeys = STANDARD_SIZE_MAP.map(s => s.euro);
      const nextSizes = [...productForm.sizes, size].sort((a, b) => {
        return (allKeys.indexOf(a) !== -1 ? allKeys.indexOf(a) : 99) - (allKeys.indexOf(b) !== -1 ? allKeys.indexOf(b) : 99);
      });
      productForm.sizes = nextSizes;

      // Ensure all variants have default stock initialized for newly activated size
      for (const v of variants) {
        if (!v.size_stock) v.size_stock = {};
        if (v.size_stock[size] === undefined) {
          v.size_stock[size] = 10;
        }
        v.stock_quantity = Object.values(v.size_stock).reduce((acc, n) => acc + (Number(n) || 0), 0);
      }
    }
  }

  function applySizePreset(preset: 'standard' | 'all') {
    const targetSizes = preset === 'standard' 
      ? ['36', '37', '38', '39', '40', '41']
      : ['35', '36', '37', '38', '39', '40', '41', '42'];

    productForm.sizes = targetSizes;
    for (const v of variants) {
      if (!v.size_stock) v.size_stock = {};
      for (const sz of targetSizes) {
        if (v.size_stock[sz] === undefined) {
          v.size_stock[sz] = 10;
        }
      }
      v.stock_quantity = targetSizes.reduce((acc, sz) => acc + (Number(v.size_stock[sz]) || 0), 0);
    }
    uiStore.addToast(`Applied ${preset} size preset (${targetSizes.join(', ')})`, 'info');
  }

  onMount(async () => {
    if (initialData) {
      populateInitialData(initialData);
    } else if (productId) {
      await loadExistingProduct(productId);
    }
    if (variants.length > 0 && !activeVariantTabId) {
      activeVariantTabId = variants[0].id || '0';
    }
  });

  function populateInitialData(data: CompleteProduct) {
    const loadedSizes = Array.isArray(data.sizes) && data.sizes.length > 0 
      ? data.sizes.map(String) 
      : ['36', '37', '38', '39', '40', '41'];

    productForm = {
      id: data.id || '',
      name: data.name || '',
      slug: data.slug || '',
      brand: data.brand || 'French Toes',
      category: data.category || 'Slippers',
      base_price: String(data.base_price || 0),
      compare_at_price: data.compare_at_price != null ? String(data.compare_at_price) : '',
      sizes: loadedSizes,
      description: data.description || '',
      status: data.status || 'draft'
    };
    slugAutoGenerated = false;

    if (data.variants && data.variants.length > 0) {
      variants = data.variants.map((v, index) => {
        let sizeStock: Record<string, number> = {};
        if (v.attributes && typeof v.attributes === 'object' && v.attributes.size_stock) {
          sizeStock = { ...v.attributes.size_stock };
        } else {
          const totalStock = v.stock_quantity ?? 50;
          const perSize = Math.max(1, Math.floor(totalStock / loadedSizes.length));
          loadedSizes.forEach(sz => { sizeStock[sz] = perSize; });
        }

        const calculatedStock = Object.values(sizeStock).reduce((acc, n) => acc + (Number(n) || 0), 0);

        return {
          id: v.id,
          sku: v.sku,
          color_name: v.color_name,
          color_slug: v.color_slug || slugify(v.color_name),
          color_hex: v.color_hex || '#000000',
          attributes: v.attributes || {},
          size_stock: sizeStock,
          price_override: v.price_override !== null && v.price_override !== undefined ? String(v.price_override) : '',
          compare_at_price: v.compare_at_price !== null && v.compare_at_price !== undefined ? String(v.compare_at_price) : '',
          stock_quantity: calculatedStock > 0 ? calculatedStock : (v.stock_quantity ?? 0),
          is_default: v.is_default ?? (index === 0),
          position: v.position ?? index,
          images: v.images || []
        };
      });
      activeVariantTabId = variants[0].id || '0';
    }
  }

  async function loadExistingProduct(id: string) {
    try {
      const { data: prod, error: pErr } = await supabase
        .from('products')
        .select('*')
        .eq('id', id)
        .single();

      if (pErr || !prod) {
        uiStore.addToast('Could not load product details', 'error');
        return;
      }

      const { data: dbVars, error: vErr } = await supabase
        .from('product_variants')
        .select('*, images:product_images(*)')
        .eq('product_id', id)
        .order('position', { ascending: true });

      const loadedVariants: LocalVariant[] = (dbVars || []).map((v: any, index: number) => ({
        id: v.id,
        sku: v.sku,
        color_name: v.color_name,
        color_slug: v.color_slug,
        color_hex: v.color_hex,
        attributes: v.attributes || {},
        size_stock: v.attributes?.size_stock || {},
        price_override: v.price_override ? String(v.price_override) : '',
        compare_at_price: v.compare_at_price ? String(v.compare_at_price) : '',
        stock_quantity: v.stock_quantity || 0,
        is_default: v.is_default,
        position: v.position ?? index,
        images: (v.images || []).sort((a: any, b: any) => (a.position ?? 0) - (b.position ?? 0))
      }));

      populateInitialData({
        ...prod,
        variants: loadedVariants as any
      });
    } catch (e: any) {
      console.error('Error loading product:', e);
      uiStore.addToast(e.message || 'Failed to load product', 'error');
    }
  }

  // Auto-generate slug when name changes if not manually modified
  function handleNameChange(newName: string) {
    productForm.name = newName;
    if (slugAutoGenerated) {
      productForm.slug = slugify(newName);
      // Auto-update first variant SKU if default
      if (variants.length > 0 && variants[0].sku.startsWith('FT-')) {
        const slugCode = slugify(newName).toUpperCase().slice(0, 8);
        const colorCode = slugify(variants[0].color_name).toUpperCase().slice(0, 4);
        variants[0].sku = `${slugCode}-${colorCode}`;
      }
    }
  }

  // Variant Management
  function addVariant() {
    const defaultColor = QUICK_PALETTE[variants.length % QUICK_PALETTE.length];
    const slugCode = (productForm.slug || 'FT').toUpperCase().slice(0, 8);
    const colorCode = slugify(defaultColor.name).toUpperCase().slice(0, 4);
    const newSku = `${slugCode}-${colorCode}-${variants.length + 1}`;

    const sizeStock: Record<string, number> = {};
    productForm.sizes.forEach(sz => { sizeStock[sz] = 10; });

    const newVariant: LocalVariant = {
      id: crypto.randomUUID(),
      sku: newSku,
      color_name: defaultColor.name,
      color_slug: slugify(defaultColor.name),
      color_hex: defaultColor.hex,
      attributes: {},
      size_stock: sizeStock,
      price_override: '',
      compare_at_price: '',
      stock_quantity: productForm.sizes.length * 10,
      is_default: variants.length === 0,
      position: variants.length,
      images: []
    };

    variants = [...variants, newVariant];
    activeVariantTabId = newVariant.id!;
  }

  function duplicateVariant(index: number) {
    const src = variants[index];
    const nextColor = QUICK_PALETTE[(index + 1) % QUICK_PALETTE.length];
    const slugCode = (productForm.slug || 'FT').toUpperCase().slice(0, 8);
    const colorCode = slugify(nextColor.name).toUpperCase().slice(0, 4);
    const newSku = `${slugCode}-${colorCode}-${variants.length + 1}`;

    const cloned: LocalVariant = {
      id: crypto.randomUUID(),
      sku: newSku,
      color_name: nextColor.name,
      color_slug: slugify(nextColor.name),
      color_hex: nextColor.hex,
      attributes: JSON.parse(JSON.stringify(src.attributes || {})),
      size_stock: JSON.parse(JSON.stringify(src.size_stock || {})),
      price_override: src.price_override,
      compare_at_price: src.compare_at_price,
      stock_quantity: src.stock_quantity,
      is_default: false, // Clone is never default
      position: variants.length,
      images: [] // images are not duplicated per requirements
    };

    variants = [...variants, cloned];
    activeVariantTabId = cloned.id!;
    uiStore.addToast(`Duplicated "${src.color_name}" as "${cloned.color_name}"`, 'info');
  }

  function removeVariant(index: number) {
    if (variants.length <= 1) {
      uiStore.addToast('A product must have at least one color variant.', 'error');
      return;
    }

    const removed = variants[index];
    const remaining = variants.filter((_, i) => i !== index);

    // If we removed the default variant, assign the first remaining one as default
    if (removed.is_default && remaining.length > 0) {
      remaining[0].is_default = true;
    }

    variants = remaining;
    if (activeVariantTabId === removed.id && variants.length > 0) {
      activeVariantTabId = variants[0].id!;
    }
    uiStore.addToast(`Removed variant "${removed.color_name}"`, 'info');
  }

  function setDefaultVariant(index: number) {
    variants = variants.map((v, i) => ({
      ...v,
      is_default: i === index
    }));
  }

  // Ensure DB record exists so images can be attached via foreign keys
  async function ensureDraftInDatabase(): Promise<boolean> {
    if (!productForm.name || !productForm.slug) {
      uiStore.addToast('Please enter product name and slug first.', 'error');
      currentStep = 1;
      return false;
    }

    if (!productForm.id) {
      productForm.id = crypto.randomUUID();
    }

    try {
      const payload = {
        product: {
          id: productForm.id,
          name: productForm.name,
          slug: productForm.slug,
          brand: productForm.brand,
          category: productForm.category,
          base_price: parseFloat(productForm.base_price) || 0,
          compare_at_price: productForm.compare_at_price ? parseFloat(productForm.compare_at_price) : null,
          sizes: productForm.sizes,
          description: productForm.description,
          status: 'draft' // ensure draft during image uploads
        },
        variants: variants.map((v, i) => ({
          id: v.id || crypto.randomUUID(),
          sku: v.sku || `${productForm.slug.toUpperCase()}-${i}`,
          color_name: v.color_name,
          color_slug: v.color_slug || slugify(v.color_name),
          color_hex: v.color_hex,
          attributes: { ...v.attributes, size_stock: v.size_stock },
          price_override: v.price_override ? parseFloat(String(v.price_override)) : null,
          compare_at_price: v.compare_at_price ? parseFloat(String(v.compare_at_price)) : null,
          stock_quantity: v.stock_quantity || 0,
          is_default: v.is_default,
          position: i
        }))
      };

      const res = await fetch('/api/admin/products/save', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload)
      });

      const resData = await res.json();
      if (!res.ok || !resData.success) {
        throw new Error(resData.error || 'Failed to initialize draft in database');
      }

      // Sync updated IDs
      if (resData.product?.id) {
        productForm.id = resData.product.id;
      }
      if (resData.variants && Array.isArray(resData.variants)) {
        variants = variants.map((v) => {
          const match = resData.variants.find((rv: any) => rv.sku === v.sku || rv.id === v.id);
          return match ? { ...v, id: match.id } : v;
        });
      }

      return true;
    } catch (err: any) {
      console.error('Draft save failed:', err);
      uiStore.addToast(err.message || 'Draft initialization error', 'error');
      return false;
    }
  }

  // Upload Images for a Variant
  async function handleFileUpload(files: FileList | File[], variantId: string) {
    if (!files || files.length === 0) return;

    const variant = variants.find(v => v.id === variantId);
    if (!variant) return;

    // Validate draft is in DB
    isUploading = true;
    uploadError = null;
    uploadProgress = 'Preparing draft for upload...';

    const draftReady = await ensureDraftInDatabase();
    if (!draftReady) {
      isUploading = false;
      uploadProgress = null;
      return;
    }

    // Refresh active variant with confirmed DB ID
    const updatedVariant = variants.find(v => v.id === variantId || v.sku === variant.sku);
    const confirmedVariantId = updatedVariant?.id || variant.id;

    const fileArray = Array.from(files);
    let uploadedCount = 0;

    for (let i = 0; i < fileArray.length; i++) {
      const file = fileArray[i];

      // Client-side file validation
      if (!file.type.startsWith('image/')) {
        uploadError = `File "${file.name}" is not an image. Only JPG, PNG, WEBP allowed.`;
        uiStore.addToast(uploadError, 'error');
        continue;
      }
      if (file.size > 15 * 1024 * 1024) {
        uploadError = `File "${file.name}" exceeds 15MB limit.`;
        uiStore.addToast(uploadError, 'error');
        continue;
      }

      uploadProgress = `Uploading ${i + 1} of ${fileArray.length}: ${file.name}...`;

      try {
        const formData = new FormData();
        formData.append('file', file);
        formData.append('product_id', productForm.id);
        formData.append('variant_id', confirmedVariantId!);
        formData.append('color_slug', updatedVariant?.color_slug || slugify(updatedVariant?.color_name || 'color'));
        formData.append('product_slug', slugify(productForm.slug));
        formData.append('alt_text', `${productForm.name} in ${updatedVariant?.color_name}`);

        const res = await fetch('/api/admin/products/upload-image', {
          method: 'POST',
          body: formData
        });

        const data = await res.json();
        if (!res.ok || !data.success) {
          throw new Error(data.error || `Upload failed for ${file.name}`);
        }

        // Add to local images list
        const newImg: DBProductImage = data.image;
        if (updatedVariant) {
          updatedVariant.images = [...(updatedVariant.images || []), newImg];
          variants = [...variants];
        }
        uploadedCount++;
      } catch (err: any) {
        console.error('Upload failed for file:', err);
        uploadError = err.message || 'Image upload failed';
        uiStore.addToast(uploadError, 'error');
      }
    }

    isUploading = false;
    uploadProgress = null;
    if (uploadedCount > 0) {
      uiStore.addToast(`Successfully uploaded ${uploadedCount} image(s) with tags & naming.`, 'success');
    }
  }

  // Delete Image
  async function handleDeleteImage(variantId: string, imageId: string, ikFileId?: string) {
    if (!confirm('Are you sure you want to delete this image?')) return;

    try {
      const res = await fetch('/api/admin/products/delete-image', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ imageId, imagekitFileId: ikFileId })
      });

      const data = await res.json();
      if (!res.ok || !data.success) {
        throw new Error(data.error || 'Failed to delete image');
      }

      // Update local state
      const variant = variants.find(v => v.id === variantId);
      if (variant) {
        variant.images = variant.images.filter(img => img.id !== imageId);
        // If the deleted one was primary, mark first remaining as primary
        if (variant.images.length > 0 && !variant.images.some(img => img.is_primary)) {
          variant.images[0].is_primary = true;
        }
        variants = [...variants];
      }

      uiStore.addToast('Image deleted.', 'info');
    } catch (err: any) {
      uiStore.addToast(err.message || 'Failed to delete image', 'error');
    }
  }

  // Set Primary Image
  async function handleSetPrimary(variantId: string, imageId: string) {
    const variant = variants.find(v => v.id === variantId);
    if (!variant) return;

    variant.images = variant.images.map(img => ({
      ...img,
      is_primary: img.id === imageId
    }));
    variants = [...variants];

    try {
      await fetch('/api/admin/products/reorder-images', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          variantId,
          imageOrders: variant.images.map((img, idx) => ({ id: img.id, position: idx, is_primary: img.id === imageId })),
          primaryImageId: imageId
        })
      });
      uiStore.addToast('Primary image updated.', 'success');
    } catch (e) {
      console.warn('Set primary warning:', e);
    }
  }

  // Drag-and-drop Image Reordering
  function handleDragStart(index: number) {
    draggedImageIndex = index;
  }

  function handleDragOver(e: DragEvent, targetIndex: number) {
    e.preventDefault();
  }

  async function handleDrop(targetIndex: number, variantId: string) {
    if (draggedImageIndex === null || draggedImageIndex === targetIndex) return;

    const variant = variants.find(v => v.id === variantId);
    if (!variant) return;

    const imagesList = [...variant.images];
    const [moved] = imagesList.splice(draggedImageIndex, 1);
    imagesList.splice(targetIndex, 0, moved);

    // Update positions
    const updatedImages = imagesList.map((img, idx) => ({
      ...img,
      position: idx
    }));

    variant.images = updatedImages;
    variants = [...variants];
    draggedImageIndex = null;

    // Persist new order
    try {
      await fetch('/api/admin/products/reorder-images', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          variantId,
          imageOrders: updatedImages.map(img => ({ id: img.id, position: img.position, is_primary: img.is_primary }))
        })
      });
    } catch (e) {
      console.warn('Reorder save warning:', e);
    }
  }

  // Validation before publishing
  interface ValidationItem {
    id: string;
    label: string;
    passed: boolean;
    errorText?: string;
  }

  const validationList = $derived.by<ValidationItem[]>(() => {
    const list: ValidationItem[] = [];

    // 1. Basic Info
    const hasName = Boolean(productForm.name.trim());
    const hasSlug = Boolean(productForm.slug.trim());
    const hasPrice = !isNaN(parseFloat(productForm.base_price)) && parseFloat(productForm.base_price) >= 0;
    list.push({
      id: 'basic-info',
      label: 'Product Title, Slug & Valid Base Price',
      passed: hasName && hasSlug && hasPrice,
      errorText: !hasName ? 'Product name is missing' : !hasSlug ? 'Product slug is missing' : !hasPrice ? 'Base price must be a valid number' : undefined
    });

    // 2. At least 1 variant
    const hasVariants = variants.length >= 1;
    list.push({
      id: 'has-variants',
      label: 'At least one color variant defined',
      passed: hasVariants,
      errorText: !hasVariants ? 'You must create at least 1 color variant.' : undefined
    });

    // 3. Exactly 1 default variant
    const defaultCount = variants.filter(v => v.is_default).length;
    list.push({
      id: 'one-default',
      label: 'Exactly one default variant selected',
      passed: defaultCount === 1,
      errorText: defaultCount === 0 ? 'Please choose one variant as the default.' : defaultCount > 1 ? 'Multiple default variants are selected.' : undefined
    });

    // 4. Unique SKUs
    const skus = variants.map(v => v.sku.trim().toUpperCase()).filter(Boolean);
    const uniqueSkus = new Set(skus);
    const allSkusFilled = variants.every(v => Boolean(v.sku.trim()));
    const skusUnique = uniqueSkus.size === variants.length && allSkusFilled;
    list.push({
      id: 'unique-skus',
      label: 'All variants have unique SKU codes',
      passed: skusUnique,
      errorText: !allSkusFilled ? 'One or more variants are missing SKUs.' : !skusUnique ? 'Duplicate SKUs found. Each SKU must be unique.' : undefined
    });

    // 5. Images per variant
    const allHaveImages = variants.every(v => v.images && v.images.length > 0);
    list.push({
      id: 'images-per-variant',
      label: 'Every variant has at least one image',
      passed: allHaveImages,
      errorText: !allHaveImages ? 'Some variants do not have any uploaded images.' : undefined
    });

    // 6. Sizes defined
    const hasSizes = Array.isArray(productForm.sizes) && productForm.sizes.length > 0;
    list.push({
      id: 'has-sizes',
      label: 'At least one shoe size configured',
      passed: hasSizes,
      errorText: !hasSizes ? 'Please select at least one shoe size for this product.' : undefined
    });

    return list;
  });

  const allValidForPublish = $derived(validationList.every(item => item.passed));

  // Commit / Save Product
  async function commitProduct(targetStatus: 'draft' | 'published') {
    if (targetStatus === 'published' && !allValidForPublish) {
      uiStore.addToast('Please resolve validation errors before publishing.', 'error');
      return;
    }

    isSaving = true;

    try {
      const payload = {
        product: {
          id: productForm.id || undefined,
          name: productForm.name.trim(),
          slug: slugify(productForm.slug),
          brand: productForm.brand.trim(),
          category: productForm.category,
          base_price: parseFloat(productForm.base_price) || 0,
          compare_at_price: productForm.compare_at_price ? parseFloat(productForm.compare_at_price) : null,
          sizes: productForm.sizes,
          description: productForm.description,
          status: targetStatus
        },
        variants: variants.map((v, i) => ({
          id: v.id,
          sku: v.sku.trim().toUpperCase(),
          color_name: v.color_name.trim(),
          color_slug: slugify(v.color_name),
          color_hex: v.color_hex,
          attributes: { ...v.attributes, size_stock: v.size_stock },
          price_override: v.price_override ? parseFloat(String(v.price_override)) : null,
          compare_at_price: v.compare_at_price ? parseFloat(String(v.compare_at_price)) : null,
          stock_quantity: Number(v.stock_quantity || 0),
          is_default: Boolean(v.is_default),
          position: i
        })),
        images: variants.flatMap(v => (v.images || []).map((img, imgIdx) => ({
          id: img.id,
          variant_id: v.id,
          imagekit_file_id: img.imagekit_file_id,
          image_url: img.image_url,
          file_name: img.file_name,
          alt_text: img.alt_text,
          position: img.position !== undefined ? img.position : imgIdx,
          is_primary: Boolean(img.is_primary)
        })))
      };

      const res = await fetch('/api/admin/products/save', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload)
      });

      const result = await res.json();

      if (!res.ok || !result.success) {
        throw new Error(result.error || 'Failed to commit product');
      }

      uiStore.addToast(
        targetStatus === 'published' 
          ? '🎉 Product published successfully!' 
          : 'Product draft saved successfully.', 
        'success'
      );

      goto('/admin/products');
    } catch (err: any) {
      console.error('Commit product failed:', err);
      uiStore.addToast(err.message || 'Error saving product', 'error');
    } finally {
      isSaving = false;
    }
  }

  // Active variant tab object in step 3
  const currentTabVariant = $derived(variants.find(v => v.id === activeVariantTabId) || variants[0]);
</script>

<div class="max-w-6xl mx-auto space-y-6 pb-20">
  <!-- Header with Steps Navigation -->
  <div class="flex flex-col md:flex-row md:items-center md:justify-between gap-4 bg-[#1a1b29] border border-white/10 rounded-2xl p-6 shadow-xl">
    <div>
      <div class="flex items-center gap-2 text-xs text-gray-400 mb-1">
        <a href="/admin/products" class="hover:text-white transition-colors">Products</a>
        <span>/</span>
        <span class="text-pink-400 font-medium">{productId ? 'Edit Product' : 'New Product Wizard'}</span>
      </div>
      <h1 class="text-2xl font-bold text-white tracking-tight">
        {productForm.name || (productId ? 'Edit Product' : 'Create New Product')}
      </h1>
    </div>

    <!-- Step Indicator Tabs -->
    <div class="flex items-center bg-[#13141f] p-1.5 rounded-xl border border-white/10 overflow-x-auto">
      {#each [
        { num: 1, title: '1. Product Info' },
        { num: 2, title: '2. Variants' },
        { num: 3, title: '3. Images' },
        { num: 4, title: '4. Review & Publish' }
      ] as step}
        <button
          type="button"
          onclick={() => currentStep = step.num as any}
          class="px-4 py-2 rounded-lg text-xs font-semibold transition-all flex items-center gap-2 whitespace-nowrap {
            currentStep === step.num
              ? 'bg-gradient-to-r from-pink-500 to-rose-400 text-white shadow-md'
              : 'text-gray-400 hover:text-white hover:bg-white/5'
          }"
        >
          <span>{step.title}</span>
        </button>
      {/each}
    </div>
  </div>

  <!-- ========================================================================= -->
  <!-- STEP 1: PRODUCT INFO -->
  <!-- ========================================================================= -->
  {#if currentStep === 1}
    <div class="bg-[#1a1b29] border border-white/10 rounded-2xl p-6 shadow-xl space-y-6">
      <div class="border-b border-white/10 pb-4">
        <h2 class="text-lg font-bold text-white">Step 1 — General Product Information</h2>
        <p class="text-xs text-gray-400 mt-0.5">Enter the core details, branding, category, and base pricing.</p>
      </div>

      <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
        <!-- Product Name -->
        <div class="space-y-2">
          <label for="prod_name" class="block text-xs font-semibold text-gray-300 uppercase tracking-wider">
            Product Title <span class="text-pink-400">*</span>
          </label>
          <input
            id="prod_name"
            type="text"
            value={productForm.name}
            oninput={(e) => handleNameChange((e.target as HTMLInputElement).value)}
            placeholder="e.g. The Cloud Slippers"
            class="w-full bg-[#13141f] border border-white/15 rounded-xl px-4 py-3 text-white placeholder-gray-500 focus:outline-none focus:border-pink-500 focus:ring-1 focus:ring-pink-500 transition-colors"
          />
        </div>

        <!-- Slug -->
        <div class="space-y-2">
          <div class="flex items-center justify-between">
            <label for="prod_slug" class="block text-xs font-semibold text-gray-300 uppercase tracking-wider">
              Slug / URL Handle <span class="text-pink-400">*</span>
            </label>
            <span class="text-[11px] text-gray-400">/products/{productForm.slug || '...'}</span>
          </div>
          <div class="relative">
            <input
              id="prod_slug"
              type="text"
              bind:value={productForm.slug}
              oninput={() => slugAutoGenerated = false}
              placeholder="e.g. the-cloud-slippers"
              class="w-full bg-[#13141f] border border-white/15 rounded-xl px-4 py-3 text-white placeholder-gray-500 focus:outline-none focus:border-pink-500 focus:ring-1 focus:ring-pink-500 transition-colors font-mono text-sm"
            />
          </div>
        </div>

        <!-- Brand -->
        <div class="space-y-2">
          <label for="prod_brand" class="block text-xs font-semibold text-gray-300 uppercase tracking-wider">
            Brand
          </label>
          <input
            id="prod_brand"
            type="text"
            bind:value={productForm.brand}
            placeholder="French Toes"
            class="w-full bg-[#13141f] border border-white/15 rounded-xl px-4 py-3 text-white placeholder-gray-500 focus:outline-none focus:border-pink-500 focus:ring-1 focus:ring-pink-500 transition-colors"
          />
        </div>

        <!-- Category -->
        <div class="space-y-2">
          <label for="prod_cat" class="block text-xs font-semibold text-gray-300 uppercase tracking-wider">
            Category
          </label>
          <div class="flex gap-2">
            <select
              id="prod_cat"
              bind:value={productForm.category}
              class="flex-1 bg-[#13141f] border border-white/15 rounded-xl px-4 py-3 text-white focus:outline-none focus:border-pink-500 focus:ring-1 focus:ring-pink-500 transition-colors"
            >
              {#each PRESET_CATEGORIES as cat}
                <option value={cat}>{cat}</option>
              {/each}
            </select>
          </div>
        </div>

        <!-- Discounted Selling Price & Regular Price (MRP) -->
        <div class="space-y-2">
          <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <!-- Discounted / Selling Price -->
            <div>
              <label for="prod_price" class="block text-xs font-semibold text-gray-300 uppercase tracking-wider mb-2">
                Discounted / Selling Price (₹) <span class="text-pink-400">*</span>
              </label>
              <div class="relative">
                <span class="absolute left-4 top-3.5 text-gray-400 font-bold">₹</span>
                <input
                  id="prod_price"
                  type="number"
                  min="0"
                  step="1"
                  bind:value={productForm.base_price}
                  placeholder="999"
                  class="w-full bg-[#13141f] border border-white/15 rounded-xl pl-8 pr-4 py-3 text-white placeholder-gray-500 focus:outline-none focus:border-pink-500 focus:ring-1 focus:ring-pink-500 transition-colors font-mono font-bold"
                />
              </div>
              <p class="text-[11px] text-gray-400 mt-1">The actual checkout price customer pays.</p>
            </div>

            <!-- Regular / Original MRP -->
            <div>
              <label for="prod_compare_price" class="block text-xs font-semibold text-gray-300 uppercase tracking-wider mb-2">
                Regular Price / MRP (₹) <span class="text-gray-400 font-normal">(Optional)</span>
              </label>
              <div class="relative">
                <span class="absolute left-4 top-3.5 text-gray-400 font-bold">₹</span>
                <input
                  id="prod_compare_price"
                  type="number"
                  min="0"
                  step="1"
                  bind:value={productForm.compare_at_price}
                  placeholder="1499"
                  class="w-full bg-[#13141f] border border-white/15 rounded-xl pl-8 pr-4 py-3 text-white placeholder-gray-500 focus:outline-none focus:border-pink-500 focus:ring-1 focus:ring-pink-500 transition-colors font-mono text-gray-300"
                />
              </div>
              <p class="text-[11px] text-gray-400 mt-1">Strikethrough original price for discount display.</p>
            </div>
          </div>
        </div>

        <!-- Status -->
        <div class="space-y-2">
          <label for="prod_status" class="block text-xs font-semibold text-gray-300 uppercase tracking-wider">
            Initial Status
          </label>
          <select
            id="prod_status"
            bind:value={productForm.status}
            class="w-full bg-[#13141f] border border-white/15 rounded-xl px-4 py-3 text-white focus:outline-none focus:border-pink-500 focus:ring-1 focus:ring-pink-500 transition-colors"
          >
            <option value="published">Published (Visible in Storefront)</option>
            <option value="draft">Draft (Hidden / In Progress)</option>
            <option value="archived">Archived</option>
          </select>
        </div>
      </div>

      <!-- Description -->
      <div class="space-y-2">
        <label for="prod_desc" class="block text-xs font-semibold text-gray-300 uppercase tracking-wider">
          Product Description
        </label>
        <textarea
          id="prod_desc"
          rows="4"
          bind:value={productForm.description}
          placeholder="Detailed craftmanship, materials, and styling notes..."
          class="w-full bg-[#13141f] border border-white/15 rounded-xl px-4 py-3 text-white placeholder-gray-500 focus:outline-none focus:border-pink-500 focus:ring-1 focus:ring-pink-500 transition-colors resize-y"
        ></textarea>
      </div>

      <!-- Available Sizes Configuration -->
      <div class="space-y-3 pt-4 border-t border-white/10">
        <div class="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-2">
          <div>
            <span class="block text-xs font-semibold text-gray-300 uppercase tracking-wider">
              Available Shoe Sizes <span class="text-pink-400">*</span>
            </span>
            <p class="text-[11px] text-gray-400">Select which sizes are manufactured / offered for this product model.</p>
          </div>
          <!-- Quick size presets -->
          <div class="flex items-center gap-2">
            <button
              type="button"
              onclick={() => applySizePreset('standard')}
              class="px-2.5 py-1 rounded-lg bg-white/5 hover:bg-white/10 text-[11px] font-medium text-gray-300 hover:text-white border border-white/10 transition-colors"
            >
              Standard 36–41
            </button>
            <button
              type="button"
              onclick={() => applySizePreset('all')}
              class="px-2.5 py-1 rounded-lg bg-white/5 hover:bg-white/10 text-[11px] font-medium text-gray-300 hover:text-white border border-white/10 transition-colors"
            >
              All (35–42)
            </button>
          </div>
        </div>

        <!-- Size Selection Chips -->
        <div class="grid grid-cols-2 sm:grid-cols-4 md:grid-cols-8 gap-2.5 pt-1">
          {#each STANDARD_SIZE_MAP as s}
            {@const isSelected = productForm.sizes.includes(s.euro)}
            <button
              type="button"
              onclick={() => toggleProductSize(s.euro)}
              class="p-2.5 rounded-xl text-center border transition-all flex flex-col items-center justify-center gap-0.5 {
                isSelected
                  ? 'bg-pink-500/20 border-pink-500 text-white shadow-lg ring-1 ring-pink-500/40'
                  : 'bg-[#13141f] border-white/10 text-gray-400 hover:border-white/20 hover:text-gray-200'
              }"
            >
              <span class="text-sm font-bold font-mono">EU {s.euro}</span>
              <span class="text-[10px] text-gray-400 font-medium">UK {s.ukIndia}</span>
              <span class="text-[9px] text-gray-500">{s.cm} cm</span>
            </button>
          {/each}
        </div>
      </div>

      <!-- Step 1 Footer -->
      <div class="flex justify-end pt-4 border-t border-white/10">
        <button
          type="button"
          onclick={() => {
            if (!productForm.name.trim()) {
              uiStore.addToast('Please enter a product title.', 'error');
              return;
            }
            currentStep = 2;
          }}
          class="px-6 py-3 rounded-xl bg-gradient-to-r from-pink-500 to-rose-400 text-white font-semibold text-sm hover:opacity-90 transition-opacity flex items-center gap-2 shadow-lg"
        >
          <span>Next: Color Variants</span>
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M5 12h14M12 5l7 7-7 7"/></svg>
        </button>
      </div>
    </div>
  {/if}

  <!-- ========================================================================= -->
  <!-- STEP 2: VARIANTS -->
  <!-- ========================================================================= -->
  {#if currentStep === 2}
    <div class="bg-[#1a1b29] border border-white/10 rounded-2xl p-6 shadow-xl space-y-6">
      <div class="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 border-b border-white/10 pb-4">
        <div>
          <h2 class="text-lg font-bold text-white">Step 2 — Color Variants</h2>
          <p class="text-xs text-gray-400 mt-0.5">Define colors, hex codes, unique SKUs, stock levels, and mark exactly one as default.</p>
        </div>
        <button
          type="button"
          onclick={addVariant}
          class="px-4 py-2.5 rounded-xl bg-pink-500/20 text-pink-300 hover:bg-pink-500/30 border border-pink-500/30 text-xs font-bold transition-colors flex items-center gap-2"
        >
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><path d="M12 5v14M5 12h14"/></svg>
          + Add Variant
        </button>
      </div>

      <!-- Variants Cards List -->
      <div class="space-y-4">
        {#each variants as variant, idx (variant.id || idx)}
          <div class="bg-[#13141f] border {variant.is_default ? 'border-pink-500/50 bg-pink-950/10' : 'border-white/10'} rounded-2xl p-5 space-y-4 transition-all">
            <!-- Card Header -->
            <div class="flex items-center justify-between">
              <div class="flex items-center gap-3">
                <span class="w-7 h-7 rounded-full border border-white/20 flex items-center justify-center text-xs font-bold text-white" style="background-color: {variant.color_hex || '#000'};">
                </span>
                <div>
                  <h3 class="font-bold text-white text-sm flex items-center gap-2">
                    {variant.color_name || 'Unnamed Color'}
                    {#if variant.is_default}
                      <span class="px-2 py-0.5 rounded-full text-[10px] font-bold bg-pink-500 text-white uppercase tracking-wider">
                        Default Variant
                      </span>
                    {/if}
                  </h3>
                  <span class="text-[11px] font-mono text-gray-400">SKU: {variant.sku || 'None'}</span>
                </div>
              </div>

              <!-- Card Action Buttons -->
              <div class="flex items-center gap-2">
                <button
                  type="button"
                  onclick={() => duplicateVariant(idx)}
                  title="Duplicate this variant's configuration"
                  class="px-3 py-1.5 rounded-lg bg-white/5 hover:bg-white/10 text-gray-300 hover:text-white text-xs font-medium transition-colors flex items-center gap-1.5 border border-white/10"
                >
                  <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg>
                  Duplicate
                </button>

                {#if !variant.is_default}
                  <button
                    type="button"
                    onclick={() => setDefaultVariant(idx)}
                    class="px-3 py-1.5 rounded-lg bg-white/5 hover:bg-white/10 text-gray-300 hover:text-pink-300 text-xs font-medium transition-colors border border-white/10"
                  >
                    Set as Default
                  </button>
                {/if}

                <button
                  type="button"
                  disabled={variants.length <= 1}
                  onclick={() => removeVariant(idx)}
                  title={variants.length <= 1 ? 'Product must have at least one variant' : 'Remove variant'}
                  class="p-2 rounded-lg bg-red-500/10 hover:bg-red-500/20 text-red-400 border border-red-500/20 transition-colors disabled:opacity-30 disabled:cursor-not-allowed"
                >
                  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"/></svg>
                </button>
              </div>
            </div>

            <!-- Card Fields Grid -->
            <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-4 pt-2 border-t border-white/5">
              <!-- Color Name -->
              <div class="space-y-1.5">
                <label for="color_name_{idx}" class="block text-[11px] font-semibold text-gray-400 uppercase tracking-wider">
                  Color Name
                </label>
                <input
                  id="color_name_{idx}"
                  type="text"
                  bind:value={variant.color_name}
                  oninput={() => {
                    variant.color_slug = slugify(variant.color_name);
                  }}
                  placeholder="e.g. Blush Pink"
                  class="w-full bg-[#1a1b29] border border-white/15 rounded-xl px-3 py-2 text-sm text-white placeholder-gray-500 focus:outline-none focus:border-pink-500"
                />
              </div>

              <!-- Color Hex Picker -->
              <div class="space-y-1.5">
                <label for="color_hex_{idx}" class="block text-[11px] font-semibold text-gray-400 uppercase tracking-wider">
                  Color Swatch (Hex)
                </label>
                <div class="flex items-center gap-2">
                  <input
                    id="color_picker_{idx}"
                    type="color"
                    bind:value={variant.color_hex}
                    class="w-10 h-9 p-0.5 rounded-lg bg-[#1a1b29] border border-white/15 cursor-pointer"
                  />
                  <input
                    id="color_hex_{idx}"
                    type="text"
                    bind:value={variant.color_hex}
                    placeholder="#f4a7c3"
                    class="w-full bg-[#1a1b29] border border-white/15 rounded-xl px-3 py-2 text-sm text-white font-mono uppercase focus:outline-none focus:border-pink-500"
                  />
                </div>
              </div>

              <!-- SKU -->
              <div class="space-y-1.5">
                <label for="color_sku_{idx}" class="block text-[11px] font-semibold text-gray-400 uppercase tracking-wider">
                  Variant SKU <span class="text-pink-400">*</span>
                </label>
                <input
                  id="color_sku_{idx}"
                  type="text"
                  bind:value={variant.sku}
                  placeholder="FT-BLUSH-01"
                  class="w-full bg-[#1a1b29] border border-white/15 rounded-xl px-3 py-2 text-sm text-white font-mono uppercase focus:outline-none focus:border-pink-500"
                />
              </div>

              <!-- Total Variant Stock Badge -->
              <div class="space-y-1.5">
                <span class="block text-[11px] font-semibold text-gray-400 uppercase tracking-wider">
                  Total Units (All Sizes)
                </span>
                <div class="w-full bg-[#1a1b29] border border-white/15 rounded-xl px-3 py-2 text-sm font-mono font-bold flex items-center justify-between {
                  variant.stock_quantity > 0 ? 'text-emerald-400' : 'text-red-400'
                }">
                  <span>{variant.stock_quantity} pcs</span>
                  <span class="text-[10px] font-normal px-2 py-0.5 rounded-full {
                    variant.stock_quantity > 0 ? 'bg-emerald-500/20 text-emerald-300' : 'bg-red-500/20 text-red-300'
                  }">
                    {variant.stock_quantity > 0 ? 'In Stock' : 'Out of Stock'}
                  </span>
                </div>
              </div>
            </div>

            <!-- Price Overrides & Presets (Optional) -->
            <div class="flex flex-wrap items-center justify-between gap-4 pt-2">
              <div class="flex flex-wrap items-center gap-4">
                <div class="flex items-center gap-2">
                  <label for="color_price_{idx}" class="text-xs text-gray-400">
                    Selling Price:
                  </label>
                  <div class="relative w-28">
                    <span class="absolute left-2 top-1 text-gray-400 text-xs font-bold">₹</span>
                    <input
                      id="color_price_{idx}"
                      type="number"
                      min="0"
                      bind:value={variant.price_override}
                      placeholder="{productForm.base_price || 'Base'}"
                      class="w-full bg-[#1a1b29] border border-white/15 rounded-lg pl-5 pr-2 py-1 text-xs text-white font-mono focus:outline-none focus:border-pink-500"
                    />
                  </div>
                </div>

                <div class="flex items-center gap-2">
                  <label for="color_compare_price_{idx}" class="text-xs text-gray-400">
                    MRP:
                  </label>
                  <div class="relative w-28">
                    <span class="absolute left-2 top-1 text-gray-400 text-xs font-bold">₹</span>
                    <input
                      id="color_compare_price_{idx}"
                      type="number"
                      min="0"
                      bind:value={variant.compare_at_price}
                      placeholder="{productForm.compare_at_price || 'Base'}"
                      class="w-full bg-[#1a1b29] border border-white/15 rounded-lg pl-5 pr-2 py-1 text-xs text-gray-300 font-mono focus:outline-none focus:border-pink-500"
                    />
                  </div>
                </div>
              </div>

              <!-- Quick Palette Chips -->
              <div class="flex items-center gap-1.5 flex-wrap">
                <span class="text-[10px] text-gray-500 mr-1">Presets:</span>
                {#each QUICK_PALETTE.slice(0, 8) as chip}
                  <button
                    type="button"
                    title="{chip.name} ({chip.hex})"
                    onclick={() => {
                      variant.color_name = chip.name;
                      variant.color_slug = slugify(chip.name);
                      variant.color_hex = chip.hex;
                    }}
                    class="w-5 h-5 rounded-full border border-white/20 hover:scale-125 transition-transform"
                    style="background-color: {chip.hex};"
                  ></button>
                {/each}
              </div>
            </div>

            <!-- Size-Wise Stock Inventory Matrix -->
            <div class="pt-3 border-t border-white/5 space-y-2">
              <div class="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-2">
                <div class="flex items-center gap-2">
                  <span class="text-[11px] font-bold text-gray-300 uppercase tracking-wider">
                    Size-Wise Inventory Matrix
                  </span>
                  <span class="text-[10px] text-gray-400">
                    (Manage stock per size for {variant.color_name})
                  </span>
                </div>

                <!-- Quick Batch Fill Buttons -->
                <div class="flex items-center gap-1.5 flex-wrap">
                  <span class="text-[10px] text-gray-500">Quick fill:</span>
                  <button
                    type="button"
                    onclick={() => fillVariantSizesWithQty(idx, 10)}
                    class="px-2 py-0.5 rounded bg-white/5 hover:bg-white/10 text-[10px] text-gray-300 font-mono border border-white/10 transition-colors"
                  >
                    10 pcs
                  </button>
                  <button
                    type="button"
                    onclick={() => fillVariantSizesWithQty(idx, 25)}
                    class="px-2 py-0.5 rounded bg-white/5 hover:bg-white/10 text-[10px] text-gray-300 font-mono border border-white/10 transition-colors"
                  >
                    25 pcs
                  </button>
                  <button
                    type="button"
                    onclick={() => fillVariantSizesWithQty(idx, 0)}
                    class="px-2 py-0.5 rounded bg-red-500/10 hover:bg-red-500/20 text-[10px] text-red-300 font-mono border border-red-500/20 transition-colors"
                  >
                    0 (Sold Out)
                  </button>
                </div>
              </div>

              <!-- Size Inventory Input Grid -->
              <div class="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-6 lg:grid-cols-8 gap-2">
                {#each productForm.sizes as sz}
                  {@const szOpt = findSizeOption(sz)}
                  {@const currentQty = getVariantSizeStock(variant, sz)}
                  <div class="bg-[#1a1b29] border {currentQty > 0 ? 'border-white/15' : 'border-red-500/30 bg-red-950/10'} rounded-xl p-2.5 space-y-1.5">
                    <div class="flex items-center justify-between text-[11px]">
                      <span class="font-bold text-white font-mono">EU {sz}</span>
                      <span class="text-gray-400 text-[10px]">{szOpt ? `UK ${szOpt.ukIndia}` : ''}</span>
                    </div>
                    <input
                      type="number"
                      min="0"
                      value={currentQty}
                      oninput={(e) => updateVariantSizeStock(idx, sz, (e.target as HTMLInputElement).value)}
                      placeholder="0"
                      class="w-full bg-[#13141f] border border-white/10 rounded-lg px-2 py-1.5 text-xs text-white font-mono text-center font-bold focus:outline-none focus:border-pink-500"
                    />
                    <div class="text-center">
                      <span class="text-[9px] font-semibold {currentQty > 0 ? 'text-emerald-400' : 'text-red-400'}">
                        {currentQty > 0 ? `${currentQty} in stock` : 'Sold Out'}
                      </span>
                    </div>
                  </div>
                {/each}
              </div>
            </div>
          </div>
        {/each}
      </div>

      <!-- Step 2 Navigation -->
      <div class="flex justify-between pt-4 border-t border-white/10">
        <button
          type="button"
          onclick={() => currentStep = 1}
          class="px-5 py-2.5 rounded-xl bg-white/5 hover:bg-white/10 text-gray-300 text-sm font-medium transition-colors"
        >
          ← Back to Info
        </button>

        <button
          type="button"
          onclick={() => {
            if (variants.length === 0) {
              uiStore.addToast('Please add at least one variant.', 'error');
              return;
            }
            if (!activeVariantTabId) {
              activeVariantTabId = variants[0].id || '0';
            }
            currentStep = 3;
          }}
          class="px-6 py-3 rounded-xl bg-gradient-to-r from-pink-500 to-rose-400 text-white font-semibold text-sm hover:opacity-90 transition-opacity flex items-center gap-2 shadow-lg"
        >
          <span>Next: Upload Images</span>
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M5 12h14M12 5l7 7-7 7"/></svg>
        </button>
      </div>
    </div>
  {/if}

  <!-- ========================================================================= -->
  <!-- STEP 3: IMAGES PER VARIANT -->
  <!-- ========================================================================= -->
  {#if currentStep === 3}
    <div class="bg-[#1a1b29] border border-white/10 rounded-2xl p-6 shadow-xl space-y-6">
      <div class="border-b border-white/10 pb-4">
        <h2 class="text-lg font-bold text-white">Step 3 — Variant Images & Media</h2>
        <p class="text-xs text-gray-400 mt-0.5">
          Upload and organize photos for each color variant. Uploads follow strict ImageKit path 
          <code class="text-pink-300 font-mono">/products/{'{slug}'}/{'{color}'}/</code> and naming convention.
        </p>
      </div>

      <!-- Variant Tabs -->
      <div class="flex items-center gap-2 border-b border-white/10 pb-2 overflow-x-auto">
        {#each variants as v}
          <button
            type="button"
            onclick={() => activeVariantTabId = v.id!}
            class="px-4 py-2.5 rounded-xl text-xs font-bold transition-all flex items-center gap-2.5 whitespace-nowrap border {
              activeVariantTabId === v.id
                ? 'bg-pink-500/20 border-pink-500 text-white shadow-md'
                : 'bg-[#13141f] border-white/10 text-gray-400 hover:text-white hover:border-white/20'
            }"
          >
            <span class="w-3.5 h-3.5 rounded-full border border-white/30" style="background-color: {v.color_hex || '#000'};"></span>
            <span>{v.color_name}</span>
            <span class="px-2 py-0.5 rounded-full text-[10px] {v.images && v.images.length > 0 ? 'bg-emerald-500/20 text-emerald-300' : 'bg-amber-500/20 text-amber-300'}">
              {v.images?.length || 0}
            </span>
          </button>
        {/each}
      </div>

      <!-- Active Variant Image Management Area -->
      {#if currentTabVariant}
        <div class="space-y-6">
          <!-- Dropzone & File Upload -->
          <div
            role="region"
            aria-label="Image dropzone"
            ondragover={(e) => e.preventDefault()}
            ondrop={(e) => {
              e.preventDefault();
              if (e.dataTransfer?.files) {
                handleFileUpload(e.dataTransfer.files, currentTabVariant.id!);
              }
            }}
            class="border-2 border-dashed border-white/20 hover:border-pink-500/50 rounded-2xl p-8 text-center bg-[#13141f] transition-all relative overflow-hidden"
          >
            {#if isUploading}
              <div class="absolute inset-0 bg-[#13141f]/90 flex flex-col items-center justify-center p-4 z-10">
                <div class="w-10 h-10 border-4 border-pink-500 border-t-transparent rounded-full animate-spin mb-3"></div>
                <p class="text-sm font-bold text-white">{uploadProgress || 'Uploading images to ImageKit...'}</p>
                <p class="text-xs text-gray-400 mt-1">Applying automatic sequence naming & tagging...</p>
              </div>
            {/if}

            <div class="max-w-md mx-auto space-y-3">
              <div class="w-12 h-12 rounded-2xl bg-pink-500/10 text-pink-400 mx-auto flex items-center justify-center">
                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="3" y="3" width="18" height="18" rx="2" ry="2"></rect><circle cx="8.5" cy="8.5" r="1.5"></circle><polyline points="21 15 16 10 5 21"></polyline></svg>
              </div>
              <h3 class="text-sm font-bold text-white">
                Drag & Drop photos for <span class="text-pink-400">{currentTabVariant.color_name}</span>
              </h3>
              <p class="text-xs text-gray-400">
                Supports JPG, PNG, WEBP up to 15MB. Files are automatically sequenced and tagged.
              </p>
              <div>
                <label class="inline-flex items-center gap-2 px-4 py-2.5 rounded-xl bg-pink-500 hover:bg-pink-600 text-white font-semibold text-xs cursor-pointer shadow-lg transition-colors">
                  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><path d="M12 5v14M5 12h14"/></svg>
                  Browse Files
                  <input
                    type="file"
                    multiple
                    accept="image/*"
                    onchange={(e) => {
                      const files = (e.target as HTMLInputElement).files;
                      if (files) handleFileUpload(files, currentTabVariant.id!);
                    }}
                    class="hidden"
                  />
                </label>
              </div>
            </div>
          </div>

          <!-- Upload Error Banner -->
          {#if uploadError}
            <div class="p-4 rounded-xl bg-red-500/10 border border-red-500/20 text-red-300 text-xs flex items-center gap-2">
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="10"></circle><line x1="12" y1="8" x2="12" y2="12"></line><line x1="12" y1="16" x2="12.01" y2="16"></line></svg>
              <span>{uploadError}</span>
            </div>
          {/if}

          <!-- Images Thumbnail Grid with Drag-to-Reorder -->
          <div>
            <div class="flex items-center justify-between mb-3">
              <h4 class="text-xs font-bold text-gray-300 uppercase tracking-wider">
                Variant Images ({currentTabVariant.images?.length || 0})
              </h4>
              <span class="text-[11px] text-gray-400">Drag thumbnails to reorder</span>
            </div>

            {#if !currentTabVariant.images || currentTabVariant.images.length === 0}
              <div class="bg-[#13141f] border border-white/10 rounded-xl p-8 text-center text-gray-500 text-xs">
                No images uploaded yet for {currentTabVariant.color_name}. Upload at least one image to proceed to publish.
              </div>
            {:else}
              <div class="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 gap-4">
                {#each currentTabVariant.images as img, imgIdx (img.id || imgIdx)}
                  <div
                    draggable="true"
                    ondragstart={() => handleDragStart(imgIdx)}
                    ondragover={(e) => handleDragOver(e, imgIdx)}
                    ondrop={() => handleDrop(imgIdx, currentTabVariant.id!)}
                    class="group relative bg-[#13141f] border {img.is_primary ? 'border-pink-500 ring-2 ring-pink-500/30' : 'border-white/15 hover:border-white/30'} rounded-xl overflow-hidden aspect-square flex flex-col justify-between p-2 shadow-md transition-all cursor-move"
                  >
                    <!-- Image Preview -->
                    <img
                      src={getImageKitUrl(img.image_url, 'w-300,q-80')}
                      alt={img.alt_text || 'Variant photo'}
                      class="absolute inset-0 w-full h-full object-cover -z-0"
                    />

                    <!-- Overlay Gradient -->
                    <div class="absolute inset-0 bg-gradient-to-t from-black/80 via-transparent to-black/60 pointer-events-none"></div>

                    <!-- Top Row Badges & Actions -->
                    <div class="relative z-10 flex items-center justify-between">
                      {#if img.is_primary}
                        <span class="px-2 py-0.5 rounded-md bg-pink-500 text-white text-[10px] font-bold flex items-center gap-1 shadow">
                          ⭐ Primary
                        </span>
                      {:else}
                        <button
                          type="button"
                          onclick={() => handleSetPrimary(currentTabVariant.id!, img.id)}
                          class="px-2 py-0.5 rounded-md bg-black/60 hover:bg-pink-500 text-white text-[10px] font-medium backdrop-blur-md opacity-0 group-hover:opacity-100 transition-opacity"
                        >
                          Set Primary
                        </button>
                      {/if}

                      <button
                        type="button"
                        onclick={() => handleDeleteImage(currentTabVariant.id!, img.id, img.imagekit_file_id)}
                        class="p-1 rounded-md bg-red-500/80 hover:bg-red-600 text-white text-xs opacity-0 group-hover:opacity-100 transition-opacity"
                        title="Delete image"
                      >
                        <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"/></svg>
                      </button>
                    </div>

                    <!-- Bottom Info -->
                    <div class="relative z-10 text-[10px] text-gray-200 truncate">
                      <p class="truncate font-mono">{img.file_name || 'image'}</p>
                      <span class="text-gray-400 text-[9px]">Pos: {imgIdx + 1}</span>
                    </div>
                  </div>
                {/each}
              </div>
            {/if}
          </div>
        </div>
      {/if}

      <!-- Step 3 Navigation -->
      <div class="flex justify-between pt-4 border-t border-white/10">
        <button
          type="button"
          onclick={() => currentStep = 2}
          class="px-5 py-2.5 rounded-xl bg-white/5 hover:bg-white/10 text-gray-300 text-sm font-medium transition-colors"
        >
          ← Back to Variants
        </button>

        <button
          type="button"
          onclick={() => currentStep = 4}
          class="px-6 py-3 rounded-xl bg-gradient-to-r from-pink-500 to-rose-400 text-white font-semibold text-sm hover:opacity-90 transition-opacity flex items-center gap-2 shadow-lg"
        >
          <span>Next: Review & Publish</span>
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M5 12h14M12 5l7 7-7 7"/></svg>
        </button>
      </div>
    </div>
  {/if}

  <!-- ========================================================================= -->
  <!-- STEP 4: REVIEW & PUBLISH -->
  <!-- ========================================================================= -->
  {#if currentStep === 4}
    <div class="space-y-6">
      <!-- Validation Checklist -->
      <div class="bg-[#1a1b29] border border-white/10 rounded-2xl p-6 shadow-xl space-y-4">
        <div class="flex items-center justify-between">
          <div>
            <h2 class="text-lg font-bold text-white">Pre-Publish Validation Checklist</h2>
            <p class="text-xs text-gray-400">All checks must pass before publishing to the live storefront.</p>
          </div>
          {#if allValidForPublish}
            <span class="px-3 py-1 rounded-full bg-emerald-500/20 text-emerald-300 text-xs font-bold border border-emerald-500/30 flex items-center gap-1.5">
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3"><polyline points="20 6 9 17 4 12"></polyline></svg>
              Ready to Publish
            </span>
          {:else}
            <span class="px-3 py-1 rounded-full bg-amber-500/20 text-amber-300 text-xs font-bold border border-amber-500/30 flex items-center gap-1.5">
              ⚠️ Incomplete Requirements
            </span>
          {/if}
        </div>

        <div class="grid grid-cols-1 sm:grid-cols-2 gap-3 pt-2">
          {#each validationList as item}
            <div class="flex items-start gap-3 p-3 rounded-xl {item.passed ? 'bg-emerald-950/20 border border-emerald-500/20' : 'bg-red-950/20 border border-red-500/20'}">
              <div class="w-5 h-5 rounded-full flex items-center justify-center shrink-0 mt-0.5 {item.passed ? 'bg-emerald-500 text-white' : 'bg-red-500 text-white'}">
                {#if item.passed}
                  <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3"><polyline points="20 6 9 17 4 12"></polyline></svg>
                {:else}
                  <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg>
                {/if}
              </div>
              <div class="text-xs">
                <p class="font-semibold {item.passed ? 'text-emerald-200' : 'text-red-200'}">{item.label}</p>
                {#if item.errorText}
                  <p class="text-red-400 mt-0.5">{item.errorText}</p>
                {/if}
              </div>
            </div>
          {/each}
        </div>
      </div>

      <!-- Live Storefront Preview -->
      <div class="bg-[#1a1b29] border border-white/10 rounded-2xl p-6 shadow-xl space-y-6">
        <div class="border-b border-white/10 pb-4">
          <span class="px-2.5 py-0.5 rounded-full bg-pink-500/20 text-pink-300 text-[10px] font-bold uppercase tracking-wider">
            Interactive Storefront Preview
          </span>
          <h2 class="text-lg font-bold text-white mt-1">Storefront Product Page Simulation</h2>
          <p class="text-xs text-gray-400">Click the color swatches below to test variant switching and image galleries in real-time.</p>
        </div>

        <!-- Storefront Simulation Container -->
        <div class="bg-white rounded-2xl p-6 md:p-8 text-gray-900 shadow-2xl">
          <div class="grid grid-cols-1 md:grid-cols-2 gap-8 lg:gap-12">
            <!-- Left: Image Gallery for Selected Variant -->
            <div class="space-y-4">
              <!-- Main Hero Image -->
              <div class="aspect-square bg-gray-100 rounded-2xl overflow-hidden relative flex items-center justify-center border border-gray-200">
                {#if previewVariant?.images && previewVariant.images.length > 0}
                  {@const activeImg = previewVariant.images[previewActiveImageIndex] || previewVariant.images[0]}
                  <img
                    src={getImageKitUrl(activeImg.image_url, 'w-800,q-85')}
                    alt={activeImg.alt_text || productForm.name}
                    class="w-full h-full object-cover"
                  />
                {:else}
                  <div class="text-center p-6 text-gray-400">
                    <svg width="48" height="48" class="mx-auto mb-2 opacity-50" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><rect x="3" y="3" width="18" height="18" rx="2" ry="2"></rect><circle cx="8.5" cy="8.5" r="1.5"></circle><polyline points="21 15 16 10 5 21"></polyline></svg>
                    <p class="text-xs font-semibold">No images uploaded for {previewVariant?.color_name}</p>
                  </div>
                {/if}
              </div>

              <!-- Thumbnails row -->
              {#if previewVariant?.images && previewVariant.images.length > 1}
                <div class="flex items-center gap-3 overflow-x-auto pb-2">
                  {#each previewVariant.images as thumb, tIdx}
                    <button
                      type="button"
                      onclick={() => previewActiveImageIndex = tIdx}
                      class="w-16 h-16 rounded-xl overflow-hidden border-2 transition-all shrink-0 {
                        previewActiveImageIndex === tIdx ? 'border-pink-500 ring-2 ring-pink-300' : 'border-gray-200 opacity-70 hover:opacity-100'
                      }"
                    >
                      <img
                        src={getImageKitUrl(thumb.image_url, 'w-150,q-75')}
                        alt="Thumbnail"
                        class="w-full h-full object-cover"
                      />
                    </button>
                  {/each}
                </div>
              {/if}
            </div>

            <!-- Right: Product Info & Variant Switcher -->
            <div class="space-y-6">
              <div>
                <span class="text-xs font-bold uppercase tracking-widest text-pink-600">{productForm.brand || 'French Toes'}</span>
                <h1 class="text-2xl lg:text-3xl font-bold text-gray-900 mt-1 font-serif">{productForm.name || 'Product Title'}</h1>
                <div class="flex items-baseline gap-3 mt-3">
                  <span class="text-2xl font-bold text-gray-900 font-mono">{previewPrice}</span>
                  {#if previewOriginalPriceNumber && previewOriginalPriceNumber > previewPriceNumber}
                    <span class="text-base text-gray-400 line-through font-mono">{previewOriginalPrice}</span>
                    <span class="px-2 py-0.5 rounded text-xs font-bold bg-pink-100 text-pink-700">
                      {Math.round(((previewOriginalPriceNumber - previewPriceNumber) / previewOriginalPriceNumber) * 100)}% OFF
                    </span>
                  {/if}
                  <span class="px-2.5 py-1 rounded-full text-xs font-bold {
                    (previewVariant?.stock_quantity ?? 0) > 0 ? 'bg-emerald-100 text-emerald-800' : 'bg-red-100 text-red-800'
                  }">
                    {(previewVariant?.stock_quantity ?? 0) > 0 ? 'In Stock' : 'Out of Stock'}
                  </span>
                </div>
              </div>

              <!-- Color Swatches Switcher -->
              <div class="space-y-3 pt-4 border-t border-gray-100">
                <div class="flex items-center justify-between">
                  <span class="text-xs font-bold uppercase tracking-wider text-gray-700">
                    Color: <span class="text-pink-600 font-semibold">{previewVariant?.color_name}</span>
                  </span>
                  <span class="text-xs font-mono text-gray-400">SKU: {previewVariant?.sku}</span>
                </div>

                <div class="flex items-center gap-3 flex-wrap">
                  {#each variants as v, vIdx}
                    <button
                      type="button"
                      onclick={() => {
                        previewSelectedVariantIndex = vIdx;
                        previewActiveImageIndex = 0;
                      }}
                      class="group relative p-1 rounded-full border-2 transition-all {
                        previewSelectedVariantIndex === vIdx 
                          ? 'border-gray-900 scale-110 shadow-sm' 
                          : 'border-transparent hover:border-gray-300'
                      }"
                    >
                      <span
                        class="block w-7 h-7 rounded-full border border-black/10 shadow-inner"
                        style="background-color: {v.color_hex || '#000'};"
                      ></span>
                    </button>
                  {/each}
                </div>
              </div>

              <!-- Size Selector Simulation -->
              <div class="space-y-3 pt-4 border-t border-gray-100">
                <div class="flex items-center justify-between">
                  <span class="text-xs font-bold uppercase tracking-wider text-gray-700">
                    Select Size (India / EU): <span class="text-pink-600 font-semibold">{previewSelectedSize ? `EU ${previewSelectedSize}` : 'None'}</span>
                  </span>
                  <span class="text-xs text-pink-600 font-semibold">Size Guide</span>
                </div>

                <div class="grid grid-cols-6 gap-2">
                  {#each productForm.sizes as sz}
                    {@const sizeStock = getVariantSizeStock(previewVariant, sz)}
                    {@const isSizeInStock = sizeStock > 0}
                    {@const isSelected = previewSelectedSize === sz}
                    <button
                      type="button"
                      disabled={!isSizeInStock}
                      onclick={() => previewSelectedSize = sz}
                      class="py-2.5 rounded-xl text-xs font-mono font-bold transition-all border relative {
                        isSelected
                          ? 'bg-gray-900 text-white border-gray-900 shadow-md'
                          : isSizeInStock
                            ? 'bg-white text-gray-800 border-gray-200 hover:border-gray-400'
                            : 'bg-gray-100 text-gray-400 border-gray-200 cursor-not-allowed opacity-60'
                      }"
                    >
                      <span>{sz}</span>
                      {#if !isSizeInStock}
                        <span class="absolute inset-0 flex items-center justify-center pointer-events-none">
                          <span class="w-full h-0.5 bg-red-400 rotate-45 transform"></span>
                        </span>
                      {/if}
                    </button>
                  {/each}
                </div>
              </div>

              <!-- Description -->
              <div class="space-y-2 pt-4 border-t border-gray-100">
                <h4 class="text-xs font-bold uppercase tracking-wider text-gray-700">About this product</h4>
                <p class="text-xs text-gray-600 leading-relaxed whitespace-pre-line">
                  {productForm.description || 'No description provided.'}
                </p>
              </div>

              <!-- Add to Cart CTA (Mock) -->
              <div class="pt-4">
                <button
                  type="button"
                  disabled={(previewVariant?.stock_quantity ?? 0) <= 0 || (productForm.sizes.length > 0 && previewSelectedSizeStock <= 0)}
                  class="w-full py-4 rounded-xl bg-gray-900 hover:bg-black text-white font-bold text-sm transition-colors shadow-lg disabled:bg-gray-300 disabled:cursor-not-allowed"
                >
                  {#if (previewVariant?.stock_quantity ?? 0) <= 0}
                    Variant Out of Stock
                  {:else if productForm.sizes.length > 0 && previewSelectedSizeStock <= 0}
                    Size {previewSelectedSize} Out of Stock
                  {:else}
                    Add to Cart — {previewPrice}
                  {/if}
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- Action Buttons Footer -->
      <div class="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 bg-[#1a1b29] border border-white/10 rounded-2xl p-6 shadow-xl">
        <button
          type="button"
          onclick={() => currentStep = 3}
          class="px-5 py-2.5 rounded-xl bg-white/5 hover:bg-white/10 text-gray-300 text-sm font-medium transition-colors"
        >
          ← Back to Images
        </button>

        <div class="flex items-center gap-3">
          <button
            type="button"
            disabled={isSaving}
            onclick={() => commitProduct('draft')}
            class="px-6 py-3 rounded-xl bg-white/10 hover:bg-white/15 text-white font-semibold text-sm transition-colors disabled:opacity-50"
          >
            {isSaving ? 'Saving Draft...' : 'Save Draft'}
          </button>

          <button
            type="button"
            disabled={isSaving || !allValidForPublish}
            onclick={() => commitProduct('published')}
            class="px-8 py-3 rounded-xl bg-gradient-to-r from-pink-500 to-rose-400 hover:from-pink-600 hover:to-rose-500 text-white font-bold text-sm shadow-xl transition-all disabled:opacity-40 disabled:cursor-not-allowed flex items-center gap-2"
          >
            {#if isSaving}
              <div class="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin"></div>
              <span>Publishing...</span>
            {:else}
              <span>Publish Product</span>
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><polyline points="20 6 9 17 4 12"></polyline></svg>
            {/if}
          </button>
        </div>
      </div>
    </div>
  {/if}
</div>
